travis:
  secure:
    BINSTAR_TOKEN: XyqWp51A4jXyzObt6r4o+koIShxYpF1ce69VnSDSt8SELEux0HpNp1aaBNd2ELfam8lrrcMIHcqcEtg6NjEqkymcL76nteCd3pkh+e7Qq57a+xt03vpn5l3dn7aQ46zx0hgWbHPRKBeGg/VFSHHIb4961HMv3veShwz0PR54R3m/wNnmSknA2e0GRmUgKgSfVPCMz8BVzuIlIS2IDv+8tbD/2oEjyeZAqmbyyQlcAtvwIQWdXmY0J4v6eyOQuNnO+3GkAi6oifbd5sBHYAKHyiqG+G11ZC5t0FP5Pm5bkuxHDAmaqKPmTQK0mtS5KE8cYVVLyA2PpClc+Sa8aCHPcX0+4N5jvw0g3H77TgWswJomvQO+82D1bo358rIMjU69L7OkkOdNK2qB87ZZAJOBJ7zLrMPuFie/A8crNNT4fycRy6hzfkBWuClM+YtI5g71MMSTwn7is1RWKYFatj78BijN4rolLyFkYVnq8OzN/07wMVJcbzk3Kp8welxJSG0YkJwf93lwZtD+dSLBWQBlyIyOlfzWZzIWUfdFa+oEqWlTh9Mqj1kia0XuxN46OCVJQpRlmFS5a4S/bwaBMcIP7k5foccdItOy+NpQu0h5AZbAZxYgZcRsDJLyk6vJlModofNN6FZhA9+U4QCpoi7FycUFM89KAVgWHNM7oVmRhvQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
