travis:
  secure:
    BINSTAR_TOKEN: kN5Dyy/vF5mXhP2M2x+qJeI3QFybeNe+H9R8cfH2QpiJrw6dEfQNxrwquBKpYuskNr3keRWSTJI1n9EdiiBHl6nIRiHnmZF4LWjXrgPZ6pYY0KTUGEPLiXNEa6qpKMF0vDONP6cRYTN5ic5nGjJrTCbbZFCvA+9TpqzJu5+NKyGmO6Vr6AmVaAYJElrL2ycH6tFoUWrcRuZbv+U2eeGwH36ExCMx6lhvcYJ0Sqn361ALbAIa7QcvNQny/3GKRIA14dhGnsvFjVSiSpVKu1nZsN8z5DE4oIG9biHD5EJG295xvhaLMmiahBYUgpkR9N0PaAixsGWGSST9618tmE5RzFVfz+cj0d8axN6/zVN4+C44vXKukGafdWrCOdTgR0mx+IYTgjnJaVGhbxhFg+aOZwSX5tvCCnfPLDH1fkqmoc+L8AldCWeTzEBj8txhihR+fsGx2gvJf29t0gfHWC3WfhEjwYxZ4WxhwepJBrdqGTkB67a1c7DEg6vShffpYwIn/KSbe514ZfRkVmEjAVTFDPs/OeYqsnvXH397hp71sqjL4PbxM0gVqYe3UlQo0dpCjEqmv5nbeB7VgnKnDdB3rWLxMK/AFwUOHvXkPp2Ysulyq5S/w6jFK50S+Oygqs5Ra2jSNMWrlagImiDLUwDOicR2uG157FNydzQgSON5U+U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
