travis:
  secure:
    BINSTAR_TOKEN: UHk2IEskgr7//lEE02GiA+jKL1dwD8Iqpma1n+miJh8Eu81a+gpU6go4vJbCWiovR1zwE4g0tgflyyU5JaeRS+n7YqBQi6Bh53XrYP3/dxnLgJzF/pId2ntFJJ1bGjc8pVHLbyJAZ6D55fKf0ALHrvuVGTN8+rBHA5n28rDQ66mOaBLjbLYBue0kC0HEGuXgQ9oRfzWxeuTK7+/pELUU47BcgGkM/7kHtaj02FTTj8DIiQ3Hyz8ukfHvkYaPfyjToRvINneo5TBFbzAOkb0kvn0MAXArlJ1L/zDv8KxtiA08ovp5Oxxh6QYQQaN0w9f1BQ0lN48+rcXx9l7E7c4trWKKiblvdeWxwykLQDB/7Ge5pgv0NTh1T4Ct9ec19QTArbxShBwE/pBn2CM5JFQmo63xG0mfbLI0rqJF14pTmdn59rQ81gUHEBwwDHUjPT73H6Djvr2bSF/GoQMmV7GHlNApwR9i1pyxXLnW+e2Ckhq6BYogKbMyUD8iX/jqwSK8g15ql1QBATnuS/vyjBZIpuHh/M4KJlGKcGIP/4r4lsJxqqzuA5jlDz7CwMFldAUxBg4DhLX/CugqiuR9QGQ0N08s3v066+n/z5v+t9PEluUo51k0KehXovLEt+0Bl8GoumMRmLNT4eKV+Q6I2vFpkWWZfKwnoSQ5IZbLtBuB8+Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
